const regionFlagBaseUrl = "https://storage.googleapis.com/gweb-mobius-cdn/region-flags/svg";

const regionFlagEntries = [
  ["AG", "Antigua & Barbuda"],
  ["AR", "Argentina"],
  ["AW", "Aruba"],
  ["BM", "Bermuda"],
  ["BO", "Bolivia"],
  ["BR", "Brasil"],
  ["BS", "Bahamas"],
  ["BZ", "Belize"],
  ["CA", "Canada"],
  ["CL", "Chile"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["DO", "Dominican Republic"],
  ["EC", "Ecuador"],
  ["GT", "Guatemala"],
  ["HN", "Honduras"],
  ["HT", "Haiti"],
  ["JM", "Jamaica"],
  ["KY", "Cayman Islands"],
  ["MX", "México"],
  ["NI", "Nicaragua"],
  ["PA", "Panama"],
  ["PE", "Perú"],
  ["PR", "Puerto Rico"],
  ["PY", "Paraguay"],
  ["SV", "El Salvador"],
  ["TT", "Trinidad & Tobago"],
  ["UY", "Uruguay"],
  ["VE", "Venezuela"],
  ["VG", "British Virgin Islands"],
  ["AE", "الإمارات العربية المتحدة"],
  ["AM", "Armenia"],
  ["AU", "Australia"],
  ["AZ", "Azerbaijan"],
  ["BD", "বাংলাদেশ"],
  ["BH", "Bahrain"],
  ["FJ", "Fiji"],
  ["GE", "Georgia"],
  ["HK", "Hong Kong SAR China"],
  ["ID", "Indonesia"],
  ["IL", "ישראל"],
  ["IN", "India"],
  ["IQ", "Iraq"],
  ["JO", "Jordan"],
  ["JP", "日本"],
  ["KG", "Kyrgyzstan"],
  ["KH", "Cambodia"],
  ["KR", "대한민국"],
  ["KW", "Kuwait"],
  ["KZ", "Kazakhstan"],
  ["LA", "Laos"],
  ["LB", "Lebanon"],
  ["LK", "Sri Lanka"],
  ["MV", "Maldives"],
  ["MY", "Malaysia"],
  ["NP", "Nepal"],
  ["NZ", "New Zealand"],
  ["OM", "Oman"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines"],
  ["PK", "Pakistan"],
  ["QA", "Qatar"],
  ["SA", "المملكة العربية السعودية"],
  ["SG", "Singapore"],
  ["TH", "ไทย"],
  ["TJ", "Tajikistan"],
  ["TM", "Turkmenistan"],
  ["TO", "Tonga"],
  ["TR", "Türkiye"],
  ["TW", "台灣"],
  ["UZ", "Uzbekistan"],
  ["VN", "Việt Nam"],
  ["YE", "Yemen"],
  ["AL", "Albania"],
  ["AO", "Angola"],
  ["AT", "Österreich"],
  ["BA", "Bosnia & Herzegovina"],
  ["BE", "Belgien"],
  ["BF", "Burkina Faso"],
  ["BG", "Bulgaria"],
  ["BJ", "Benin"],
  ["BW", "Botswana"],
  ["CH", "Schweiz"],
  ["CI", "Côte d’Ivoire"],
  ["CM", "Cameroon"],
  ["CV", "Cape Verde"],
  ["CY", "Cyprus"],
  ["CZ", "Česko"],
  ["DE", "Deutschland"],
  ["DK", "Danmark"],
  ["DZ", "Algeria"],
  ["EE", "Estonia"],
  ["EG", "مصر"],
  ["ES", "España"],
  ["FI", "Suomi"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GB", "United Kingdom"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GR", "Ελλάδα"],
  ["GW", "Guinea-Bissau"],
  ["HR", "Croatia"],
  ["HU", "Magyarország"],
  ["IE", "Ireland"],
  ["IS", "Iceland"],
  ["IT", "Italia"],
  ["KE", "Kenya"],
  ["LI", "Liechtenstein"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["LV", "Latvia"],
  ["MA", "Morocco"],
  ["MC", "Monaco"],
  ["MD", "Moldova"],
  ["MK", "North Macedonia"],
  ["ML", "Mali"],
  ["MT", "Malta"],
  ["MU", "Mauritius"],
  ["MZ", "Mozambique"],
  ["NA", "Namibia"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NL", "Nederland"],
  ["NO", "Norge"],
  ["PL", "Polska"],
  ["PT", "Portugal"],
  ["RO", "România"],
  ["RS", "Serbia"],
  ["RW", "Rwanda"],
  ["SC", "Seychelles"],
  ["SE", "Sverige"],
  ["SI", "Slovenia"],
  ["SK", "Slovakia"],
  ["SL", "Sierra Leone"],
  ["SM", "San Marino"],
  ["SN", "Senegal"],
  ["TG", "Togo"],
  ["TN", "Tunisia"],
  ["TZ", "Tanzania"],
  ["UA", "Україна"],
  ["UG", "Uganda"],
  ["ZA", "South Africa"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
] as const;

export type RegionFlagCode = (typeof regionFlagEntries)[number][0];

export type RegionFlag = {
  code: RegionFlagCode;
  src: string;
  element: "img";
  type: "url";
  alt: string;
};

export const regionFlags = regionFlagEntries.map(([code, alt]) => ({
  code,
  src: `${regionFlagBaseUrl}/${code}.svg`,
  element: "img",
  type: "url",
  alt,
})) satisfies RegionFlag[];

export const regionFlagsByCode = Object.fromEntries(
  regionFlags.map((flag) => [flag.code, flag])
) as Record<RegionFlagCode, RegionFlag>;

export function getRegionFlag(code: RegionFlagCode) {
  return regionFlagsByCode[code];
}
