import type { ComponentType, SVGProps } from "react";
import { AddRegular } from "@fluentui/react-icons/svg/add";
import { ArrowRightRegular } from "@fluentui/react-icons/svg/arrow-right";
import { ArrowUpRightRegular } from "@fluentui/react-icons/svg/arrow-up-right";
import { BookOpenRegular } from "@fluentui/react-icons/svg/book-open";
import { BookRegular } from "@fluentui/react-icons/svg/book";
import { BoxRegular } from "@fluentui/react-icons/svg/box";
import { BranchRegular } from "@fluentui/react-icons/svg/branch";
import { BuildingRegular } from "@fluentui/react-icons/svg/building";
import { CheckmarkCircleRegular } from "@fluentui/react-icons/svg/checkmark-circle";
import { CheckmarkRegular } from "@fluentui/react-icons/svg/checkmark";
import { ChevronDownRegular } from "@fluentui/react-icons/svg/chevron-down";
import { ChevronRightRegular } from "@fluentui/react-icons/svg/chevron-right";
import { CodeRegular } from "@fluentui/react-icons/svg/code";
import { CompassNorthwestRegular } from "@fluentui/react-icons/svg/compass-northwest";
import { CopyRegular } from "@fluentui/react-icons/svg/copy";
import { DatabaseRegular } from "@fluentui/react-icons/svg/database";
import { DismissRegular } from "@fluentui/react-icons/svg/dismiss";
import { DocumentCheckmarkRegular } from "@fluentui/react-icons/svg/document-checkmark";
import { FingerprintRegular } from "@fluentui/react-icons/svg/fingerprint";
import { FlashRegular } from "@fluentui/react-icons/svg/flash";
import { FlowRegular } from "@fluentui/react-icons/svg/flow";
import { GaugeRegular } from "@fluentui/react-icons/svg/gauge";
import { GlobeSurfaceRegular } from "@fluentui/react-icons/svg/globe-surface";
import { GlobeRegular } from "@fluentui/react-icons/svg/globe";
import { HatGraduationRegular } from "@fluentui/react-icons/svg/hat-graduation";
import { HeadsetRegular } from "@fluentui/react-icons/svg/headset";
import { HeartRegular } from "@fluentui/react-icons/svg/heart";
import { KeyRegular } from "@fluentui/react-icons/svg/key";
import { LayerRegular } from "@fluentui/react-icons/svg/layer";
import { LayoutColumnThreeRegular } from "@fluentui/react-icons/svg/layout-column-three";
import { LockClosedRegular } from "@fluentui/react-icons/svg/lock-closed";
import { MailRegular } from "@fluentui/react-icons/svg/mail";
import { NavigationRegular } from "@fluentui/react-icons/svg/navigation";
import { PeopleRegular } from "@fluentui/react-icons/svg/people";
import { PulseRegular } from "@fluentui/react-icons/svg/pulse";
import { ReceiptRegular } from "@fluentui/react-icons/svg/receipt";
import { RewardRegular } from "@fluentui/react-icons/svg/reward";
import { RocketRegular } from "@fluentui/react-icons/svg/rocket";
import { SearchRegular } from "@fluentui/react-icons/svg/search";
import { ServerRegular } from "@fluentui/react-icons/svg/server";
import { ShieldCheckmarkRegular } from "@fluentui/react-icons/svg/shield-checkmark";
import { ShieldRegular } from "@fluentui/react-icons/svg/shield";
import { SparkleRegular } from "@fluentui/react-icons/svg/sparkle";
import { StoreMicrosoftRegular } from "@fluentui/react-icons/svg/store-microsoft";
import { SubtractRegular } from "@fluentui/react-icons/svg/subtract";
import { TargetRegular } from "@fluentui/react-icons/svg/target";
import { WalletRegular } from "@fluentui/react-icons/svg/wallet";
import { WindowConsoleRegular } from "@fluentui/react-icons/svg/window-console";
import { WrenchRegular } from "@fluentui/react-icons/svg/wrench";

export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const Activity = PulseRegular;
export const AlertTriangle = ShieldRegular;
export const ArrowRight = ArrowRightRegular;
export const ArrowUpRight = ArrowUpRightRegular;
export const Award = RewardRegular;
export const BarChart3 = GaugeRegular;
export const BellRing = PulseRegular;
export const Book = BookRegular;
export const BookOpen = BookOpenRegular;
export const Blocks = BoxRegular;
export const Building2 = BuildingRegular;
export const Check = CheckmarkRegular;
export const CheckCircle2 = CheckmarkCircleRegular;
export const ChevronDown = ChevronDownRegular;
export const ChevronRight = ChevronRightRegular;
export const CircleAlert = ShieldRegular;
export const Clock = PulseRegular;
export const Code2 = CodeRegular;
export const Compass = CompassNorthwestRegular;
export const Copy = CopyRegular;
export const CreditCard = WalletRegular;
export const Database = DatabaseRegular;
export const FileCheck = DocumentCheckmarkRegular;
export const FileCode2 = CodeRegular;
export const Fingerprint = FingerprintRegular;
export const Gauge = GaugeRegular;
export const Globe = GlobeRegular;
export const Globe2 = GlobeSurfaceRegular;
export const GitBranch = BranchRegular;
export const GraduationCap = HatGraduationRegular;
export const HardDrive = ServerRegular;
export const HeadphonesIcon = HeadsetRegular;
export const Heart = HeartRegular;
export const KeyRound = KeyRegular;
export const Layers = LayerRegular;
export const LayoutDashboard = LayoutColumnThreeRegular;
export const Lock = LockClosedRegular;
export const LockKeyhole = LockClosedRegular;
export const LogOut = ArrowRightRegular;
export const Mail = MailRegular;
export const Menu = NavigationRegular;
export const MessageCircle = PeopleRegular;
export const Minus = SubtractRegular;
export const Network = FlowRegular;
export const Package = BoxRegular;
export const Phone = HeadsetRegular;
export const Plus = AddRegular;
export const RadioTower = PulseRegular;
export const Receipt = ReceiptRegular;
export const ReceiptText = ReceiptRegular;
export const Rocket = RocketRegular;
export const Search = SearchRegular;
export const Server = ServerRegular;
export const ServerCog = ServerRegular;
export const Shield = ShieldRegular;
export const ShieldAlert = ShieldRegular;
export const ShieldCheck = ShieldCheckmarkRegular;
export const Sparkles = SparkleRegular;
export const Store = StoreMicrosoftRegular;
export const Target = TargetRegular;
export const Terminal = WindowConsoleRegular;
export const TrendingUp = ArrowUpRightRegular;
export const Users = PeopleRegular;
export const Users2 = PeopleRegular;
export const Wallet = WalletRegular;
export const WifiOff = GlobeRegular;
export const Workflow = FlowRegular;
export const Wrench = WrenchRegular;
export const X = DismissRegular;
export const Zap = FlashRegular;
